# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/Genesys_axi_smc_0.xci
# IP: The module: 'Genesys_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/bd_9714.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_0/bd_9714_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_1/bd_9714_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_2/bd_9714_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_3/bd_9714_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_4/bd_9714_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_5/bd_9714_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_6/bd_9714_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_7/bd_9714_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_8/bd_9714_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_9/bd_9714_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_10/bd_9714_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_11/bd_9714_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_12/bd_9714_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_13/bd_9714_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_14/bd_9714_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_15/bd_9714_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_16/bd_9714_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_17/bd_9714_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_18/bd_9714_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_19/bd_9714_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_20/bd_9714_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_21/bd_9714_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_22/bd_9714_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_23/bd_9714_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_24/bd_9714_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_25/bd_9714_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_26/bd_9714_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_27/bd_9714_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_28/bd_9714_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_29/bd_9714_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_30/bd_9714_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_31/bd_9714_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_32/bd_9714_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_33/bd_9714_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_34/bd_9714_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_35/bd_9714_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_36/bd_9714_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_37/bd_9714_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_38/bd_9714_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_39/bd_9714_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_40/bd_9714_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_41/bd_9714_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_42/bd_9714_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_43/bd_9714_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_44/bd_9714_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_45/bd_9714_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_46/bd_9714_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_1/bd_9714_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_1/bd_9714_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_2/bd_9714_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_2/bd_9714_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_3/bd_9714_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_3/bd_9714_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_4/bd_9714_arsw_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_5/bd_9714_rsw_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_6/bd_9714_awsw_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_7/bd_9714_wsw_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_8/bd_9714_bsw_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_12/bd_9714_s00a2s_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_13/bd_9714_sarn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_14/bd_9714_srn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_15/bd_9714_sawn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_16/bd_9714_swn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_17/bd_9714_sbn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_21/bd_9714_s01a2s_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_22/bd_9714_sarn_1_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_23/bd_9714_srn_1_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_27/bd_9714_s02a2s_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_28/bd_9714_sarn_2_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_29/bd_9714_srn_2_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_30/bd_9714_sawn_1_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_31/bd_9714_swn_1_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_32/bd_9714_sbn_1_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_33/bd_9714_m00s2a_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_34/bd_9714_m00arn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_35/bd_9714_m00rn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_36/bd_9714_m00awn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_37/bd_9714_m00wn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_38/bd_9714_m00bn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_40/bd_9714_m01s2a_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_41/bd_9714_m01arn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_42/bd_9714_m01rn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_43/bd_9714_m01awn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_44/bd_9714_m01wn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_45/bd_9714_m01bn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Genesys_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/Genesys_axi_smc_0.xci
# IP: The module: 'Genesys_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/bd_9714.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_0/bd_9714_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_1/bd_9714_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_2/bd_9714_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_3/bd_9714_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_4/bd_9714_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_5/bd_9714_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_6/bd_9714_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_7/bd_9714_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_8/bd_9714_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_9/bd_9714_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_10/bd_9714_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_11/bd_9714_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_12/bd_9714_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_13/bd_9714_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_14/bd_9714_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_15/bd_9714_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_16/bd_9714_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_17/bd_9714_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_18/bd_9714_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_19/bd_9714_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_20/bd_9714_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_21/bd_9714_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_22/bd_9714_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_23/bd_9714_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_24/bd_9714_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_25/bd_9714_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_26/bd_9714_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_27/bd_9714_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_28/bd_9714_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_29/bd_9714_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_30/bd_9714_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_31/bd_9714_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_32/bd_9714_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_33/bd_9714_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_34/bd_9714_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_35/bd_9714_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_36/bd_9714_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_37/bd_9714_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_38/bd_9714_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_39/bd_9714_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_40/bd_9714_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_41/bd_9714_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_42/bd_9714_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_43/bd_9714_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_44/bd_9714_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_45/bd_9714_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_46/bd_9714_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_1/bd_9714_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_1/bd_9714_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_2/bd_9714_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_2/bd_9714_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_3/bd_9714_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_3/bd_9714_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_4/bd_9714_arsw_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_5/bd_9714_rsw_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_6/bd_9714_awsw_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_7/bd_9714_wsw_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_8/bd_9714_bsw_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_12/bd_9714_s00a2s_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_13/bd_9714_sarn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_14/bd_9714_srn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_15/bd_9714_sawn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_16/bd_9714_swn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_17/bd_9714_sbn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_21/bd_9714_s01a2s_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_22/bd_9714_sarn_1_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_23/bd_9714_srn_1_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_27/bd_9714_s02a2s_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_28/bd_9714_sarn_2_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_29/bd_9714_srn_2_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_30/bd_9714_sawn_1_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_31/bd_9714_swn_1_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_32/bd_9714_sbn_1_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_33/bd_9714_m00s2a_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_34/bd_9714_m00arn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_35/bd_9714_m00rn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_36/bd_9714_m00awn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_37/bd_9714_m00wn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_38/bd_9714_m00bn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_40/bd_9714_m01s2a_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_41/bd_9714_m01arn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_42/bd_9714_m01rn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_43/bd_9714_m01awn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_44/bd_9714_m01wn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/bd_0/ip/ip_45/bd_9714_m01bn_0_ooc.xdc

# XDC: c:/Users/xujia/Genesys/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Genesys_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
