# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Genesys/Genesys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Genesys || ORIG_REF_NAME==Genesys} -quiet] -quiet

# IP: bd/Genesys/ip/Genesys_mig_7series_0_0/Genesys_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Genesys_mig_7series_0_0 || ORIG_REF_NAME==Genesys_mig_7series_0_0} -quiet] -quiet

# IP: bd/Genesys/ip/Genesys_microblaze_0_0/Genesys_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Genesys_microblaze_0_0 || ORIG_REF_NAME==Genesys_microblaze_0_0} -quiet] -quiet

# IP: bd/Genesys/ip/Genesys_axi_uartlite_0_0/Genesys_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Genesys_axi_uartlite_0_0 || ORIG_REF_NAME==Genesys_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Genesys/ip/Genesys_axi_gpio_0_0/Genesys_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Genesys_axi_gpio_0_0 || ORIG_REF_NAME==Genesys_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Genesys/ip/Genesys_axi_bram_ctrl_0_0/Genesys_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Genesys_axi_bram_ctrl_0_0 || ORIG_REF_NAME==Genesys_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/Genesys/ip/Genesys_dlmb_v10_0/Genesys_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Genesys_dlmb_v10_0 || ORIG_REF_NAME==Genesys_dlmb_v10_0} -quiet] -quiet

# IP: bd/Genesys/ip/Genesys_ilmb_v10_0/Genesys_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Genesys_ilmb_v10_0 || ORIG_REF_NAME==Genesys_ilmb_v10_0} -quiet] -quiet

# IP: bd/Genesys/ip/Genesys_dlmb_bram_if_cntlr_0/Genesys_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Genesys_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Genesys_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Genesys/ip/Genesys_ilmb_bram_if_cntlr_0/Genesys_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Genesys_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Genesys_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Genesys/ip/Genesys_lmb_bram_0/Genesys_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Genesys_lmb_bram_0 || ORIG_REF_NAME==Genesys_lmb_bram_0} -quiet] -quiet

# IP: bd/Genesys/ip/Genesys_lmb_v10_0/Genesys_lmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Genesys_lmb_v10_0 || ORIG_REF_NAME==Genesys_lmb_v10_0} -quiet] -quiet

# IP: bd/Genesys/ip/Genesys_mdm_1_0/Genesys_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Genesys_mdm_1_0 || ORIG_REF_NAME==Genesys_mdm_1_0} -quiet] -quiet

# IP: bd/Genesys/ip/Genesys_rst_mig_7series_0_100M_0/Genesys_rst_mig_7series_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Genesys_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==Genesys_rst_mig_7series_0_100M_0} -quiet] -quiet

# IP: bd/Genesys/ip/Genesys_axi_bram_ctrl_0_bram_0/Genesys_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Genesys_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==Genesys_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/Genesys/ip/Genesys_axi_smc_0/Genesys_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Genesys_axi_smc_0 || ORIG_REF_NAME==Genesys_axi_smc_0} -quiet] -quiet

# IP: bd/Genesys/ip/Genesys_xbar_0/Genesys_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Genesys_xbar_0 || ORIG_REF_NAME==Genesys_xbar_0} -quiet] -quiet

# IP: bd/Genesys/ip/Genesys_microblaze_0_axi_periph_0/Genesys_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Genesys_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Genesys_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/Genesys/ip/Genesys_system_ila_0/Genesys_system_ila_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Genesys_system_ila_0 || ORIG_REF_NAME==Genesys_system_ila_0} -quiet] -quiet

# IP: bd/Genesys/ip/Genesys_rst_mig_7series_0_225M_0/Genesys_rst_mig_7series_0_225M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Genesys_rst_mig_7series_0_225M_0 || ORIG_REF_NAME==Genesys_rst_mig_7series_0_225M_0} -quiet] -quiet

# XDC: bd/Genesys/Genesys_ooc.xdc
